# Generated by Django 5.0.9 on 2025-05-21 04:18

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("extras", "0116_custom_link_button_color"),
        ("tenancy", "0015_contactassignment_rename_content_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("account_id", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aws_accounts",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS Account",
                "verbose_name_plural": "AWS Accounts",
                "ordering": ("account_id", "name"),
            },
        ),
    ]
