# Generated by Django 5.0.9 on 2025-05-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsaccount",
            name="parent_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_accounts",
                to="netbox_aws_resources_plugin.awsaccount",
            ),
        ),
    ]
