# Generated by Django 5.0.9 on 2025-05-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0003_alter_awsaccount_name_awsvpc_awssubnet_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awsloadbalancer",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveConstraint(
            model_name="awsloadbalancer",
            name="unique_awsloadbalancer_account_region_name",
        ),
        migrations.AddField(
            model_name="awsloadbalancer",
            name="subnets",
            field=models.ManyToManyField(
                blank=True, related_name="load_balancers", to="netbox_aws_resources_plugin.awssubnet"
            ),
        ),
        migrations.AlterField(
            model_name="awsloadbalancer",
            name="aws_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="account_load_balancers",
                to="netbox_aws_resources_plugin.awsaccount",
            ),
        ),
        migrations.AlterField(
            model_name="awsloadbalancer",
            name="scheme",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="awsloadbalancer",
            name="state",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="awsloadbalancer",
            name="type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="awsloadbalancer",
            name="vpc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vpc_load_balancers",
                to="netbox_aws_resources_plugin.awsvpc",
            ),
        ),
    ]
