# Generated by Django 5.0.9 on 2025-05-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0004_alter_awsloadbalancer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsloadbalancer",
            name="arn",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
