# Generated by Django 5.0.9 on 2025-05-22 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0005_alter_awsloadbalancer_arn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awssubnet",
            name="aws_vpc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subnets",
                to="netbox_aws_resources_plugin.awsvpc",
            ),
        ),
        migrations.AlterField(
            model_name="awssubnet",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="awssubnet",
            name="subnet_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="awsvpc",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="awsvpc",
            name="vpc_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
