# Generated by Django 5.0.9 on 2025-05-22 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0069_gfk_indexes"),
        ("netbox_aws_resources_plugin", "0006_alter_awssubnet_aws_vpc_alter_awssubnet_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsvpc",
            name="cidr_block",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name="aws_vpc_primary_cidr", to="ipam.prefix"
            ),
        ),
    ]
