# Generated by Django 5.0.9 on 2025-05-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0007_alter_awsvpc_cidr_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsaccount",
            name="account_id",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
