# Generated by Django 5.0.9 on 2025-05-29 05:47

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0116_custom_link_button_color"),
        ("netbox_aws_resources_plugin", "0008_alter_awsaccount_account_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSTargetGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=255)),
                ("arn", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("region", models.CharField(max_length=50)),
                ("protocol", models.CharField(max_length=10)),
                ("port", models.PositiveIntegerField()),
                ("target_type", models.CharField(max_length=10)),
                ("health_check_protocol", models.CharField(blank=True, max_length=10, null=True)),
                ("health_check_port", models.CharField(blank=True, default="traffic-port", max_length=20, null=True)),
                ("health_check_path", models.CharField(blank=True, max_length=255, null=True)),
                ("health_check_interval_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("health_check_timeout_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("healthy_threshold_count", models.PositiveIntegerField(blank=True, null=True)),
                ("unhealthy_threshold_count", models.PositiveIntegerField(blank=True, null=True)),
                ("state", models.CharField(default="active", max_length=30)),
                (
                    "aws_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_groups",
                        to="netbox_aws_resources_plugin.awsaccount",
                    ),
                ),
                (
                    "load_balancers",
                    models.ManyToManyField(
                        blank=True, related_name="target_groups", to="netbox_aws_resources_plugin.awsloadbalancer"
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "vpc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="target_groups",
                        to="netbox_aws_resources_plugin.awsvpc",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS Target Group",
                "verbose_name_plural": "AWS Target Groups",
                "ordering": ("name",),
            },
        ),
    ]
