# Generated by Django 5.0.9 on 2025-05-29 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0009_awstargetgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsloadbalancer",
            name="vpc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vpc_load_balancers",
                to="netbox_aws_resources_plugin.awsvpc",
            ),
        ),
        migrations.AlterField(
            model_name="awstargetgroup",
            name="vpc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="target_groups",
                to="netbox_aws_resources_plugin.awsvpc",
            ),
        ),
    ]
