# Generated by Django 5.2.4 on 2025-07-23 05:31

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0129_fix_script_paths"),
        ("netbox_aws_resources_plugin", "0010_alter_awsloadbalancer_vpc_alter_awstargetgroup_vpc"),
        ("virtualization", "0048_populate_mac_addresses"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSEC2Instance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=255)),
                ("instance_id", models.CharField(max_length=24, unique=True)),
                ("region", models.CharField(max_length=50)),
                ("instance_type", models.CharField(blank=True, max_length=255)),
                ("state", models.CharField(blank=True, max_length=30)),
                (
                    "aws_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ec2_instances",
                        to="netbox_aws_resources_plugin.awsaccount",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "virtual_machine",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aws_ec2_instance",
                        to="virtualization.virtualmachine",
                    ),
                ),
                (
                    "vpc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ec2_instances",
                        to="netbox_aws_resources_plugin.awsvpc",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS EC2 Instance",
                "verbose_name_plural": "AWS EC2 Instances",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AWSRDSInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=255)),
                ("instance_id", models.CharField(max_length=255, unique=True)),
                ("region", models.CharField(max_length=50)),
                ("instance_class", models.CharField(blank=True, max_length=255)),
                ("engine", models.CharField(blank=True, max_length=50)),
                ("engine_version", models.CharField(blank=True, max_length=50)),
                ("state", models.CharField(blank=True, max_length=50)),
                (
                    "aws_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rds_instances",
                        to="netbox_aws_resources_plugin.awsaccount",
                    ),
                ),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "virtual_machine",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aws_rds_instance",
                        to="virtualization.virtualmachine",
                    ),
                ),
                (
                    "vpc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rds_instances",
                        to="netbox_aws_resources_plugin.awsvpc",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS RDS Instance",
                "verbose_name_plural": "AWS RDS Instances",
                "ordering": ("name",),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
