# Generated by Django 5.2.4 on 2025-07-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0011_awsec2instance_awsrdsinstance"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsec2instance",
            name="estimated_cost_usd_hourly",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="awsrdsinstance",
            name="estimated_cost_usd_hourly",
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
