# Generated by Django 5.2.4 on 2025-07-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_aws_resources_plugin", "0012_awsec2instance_estimated_cost_usd_hourly_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsec2instance",
            name="subnet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ec2_instances",
                to="netbox_aws_resources_plugin.awssubnet",
            ),
        ),
        migrations.AddField(
            model_name="awsrdsinstance",
            name="subnet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rds_instances",
                to="netbox_aws_resources_plugin.awssubnet",
            ),
        ),
        migrations.AlterField(
            model_name="awsec2instance",
            name="instance_id",
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="awsec2instance",
            name="vpc",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ec2_instances",
                to="netbox_aws_resources_plugin.awsvpc",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="awsrdsinstance",
            name="instance_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="awsrdsinstance",
            name="vpc",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rds_instances",
                to="netbox_aws_resources_plugin.awsvpc",
            ),
            preserve_default=False,
        ),
    ]
