# Generated by Django 5.2.4 on 2025-07-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipam", "0081_remove_service_device_virtual_machine_add_parent_gfk_index"),
        ("netbox_aws_resources_plugin", "0013_awsec2instance_subnet_awsrdsinstance_subnet_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awstargetgroup",
            name="port",
        ),
        migrations.RemoveField(
            model_name="awstargetgroup",
            name="protocol",
        ),
        migrations.AddField(
            model_name="awstargetgroup",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aws_target_groups",
                to="ipam.service",
            ),
        ),
    ]
